// <auto-generated />
using BM_Blazor_Nov20.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BM_Blazor_Nov20.Migrations
{
    [DbContext(typeof(ClientListDbContext))]
    partial class ClientListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BM_Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraColumn1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraColumn2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraColumn3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraColumn4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraColumn5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraColumn6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
